name: LogicChatManager
version: '${project.parent.version}'
main: de.frinshhd.logicchatmanagerspigot.SpigotMain
api-version: '1.20'

permissions:
  logicchatmanager.command.chat:
    default: op
  logicchatmanager.command.chat.help:
    default: op
  logicchatmanager.command.chat.clear:
    default: op